---

- name: Install service file
  template:
    src: herotube.service
    dest: /etc/systemd/system/herotube.service
    owner: root
    group: root
  notify:
    - restart service

- name: Clone repo and update
  git:
    repo: "{{ git_repo }}"
    dest: "{{ install_dir }}"
    clone: yes
    update: yes
  become: yes
  become_user: "{{ user }}"
  notify:
    - restart service

- name: Create venv and install requirements
  pip:
    name: "."
    virtualenv: "{{ install_dir }}/pyenv"
    chdir: "{{ install_dir }}"
  become: yes
  become_user: "{{ user }}"
  notify:
    - restart service

- name: Run migrate
  command: "{{ venv_python }} herotube migrate"
  become: yes
  become_user: "{{ user }}"
  args:
    chdir: "{{ install_dir }}"
  notify:
    - restart service

- name: Run import
  command: "{{ venv_python }} herotube import"
  become: yes
  become_user: "{{ user }}"
  args:
    chdir: "{{ install_dir }}"
  notify:
    - restart service
  when: import is defined and import
